### ISSUE TITLE
Weather geolocation crashes on device without gapps

### ISSUE THREAD

**Issue by mochaaP** [8bitPit/Niagara-Issues#2108]
## Test environment

- Device: Huawei ELS-AN00

      [ro.build.display.id]: [ELS-AN00 2.0.0.276(C00E230R3P6)]
      [ro.build.description]: [ELS-AN00-user 102.0.0 HUAWEIELS-AN00 276-CHN-LGRP3 release-keys]
      [ro.build.fingerprint]: [HUAWEI/ELS-AN00/HWELS:10/HUAWEIELS-AN00/102.0.0.276C00:user/release-keys]
- Launcher version: Niagara v1.8.0 from GitHub release

## Steps to reproduce

1. Open GPS and grant Niagara Launcher with `COARSE_LOCATION` (declared in AndroidManifest, impossible to grant `FINE_LOCATION`)
2. Enable Weather and Automatic location
3. Crash

<details>

<summary>Logcat</summary>

```java
11-04 15:21:24.684 11259 11259 E AndroidRuntime: FATAL EXCEPTION: main
11-04 15:21:24.684 11259 11259 E AndroidRuntime: Process: bitpit.launcher, PID: 11259
11-04 15:21:24.684 11259 11259 E AndroidRuntime: java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.
11-04 15:21:24.684 11259 11259 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2091)
11-04 15:21:24.684 11259 11259 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2059)
11-04 15:21:24.684 11259 11259 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2007)
11-04 15:21:24.684 11259 11259 E AndroidRuntime: 	at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:1151)
11-04 15:21:24.684 11259 11259 E AndroidRuntime: 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1038)
11-04 15:21:24.684 11259 11259 E AndroidRuntime: 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:577)
11-04 15:21:24.684 11259 11259 E AndroidRuntime: 	at b.RIE8qNpwkcu.kt1Nuiq7lgI8CvQUgJgJ3oh(SourceFile:85)
11-04 15:21:24.684 11259 11259 E AndroidRuntime: 	at b.RIE8qNpwkcu.FZuQK3NYdNSH(Unknown Source:12)
11-04 15:21:24.684 11259 11259 E AndroidRuntime: 	at b.cHbwx16qRbkeFQ.tcvfH5hFPIgkkflQf(SourceFile:32)
11-04 15:21:24.684 11259 11259 E AndroidRuntime: 	at b.cHbwx16qRbkeFQ.imuzWALUH9c(SourceFile:81)
11-04 15:21:24.684 11259 11259 E AndroidRuntime: 	at b.z2IRYKffqg8tA2LgJ6xzSymW9.kt1Nuiq7lgI8CvQUgJgJ3oh(SourceFile:233)
11-04 15:21:24.684 11259 11259 E AndroidRuntime: 	at b.z2IRYKffqg8tA2LgJ6xzSymW9.W7LU5Bzfu6jNksnqCsdj6RDuV(Unknown Source:27)
11-04 15:21:24.684 11259 11259 E AndroidRuntime: 	at b.RaEuqAIENuiZUxk.kt1Nuiq7lgI8CvQUgJgJ3oh(SourceFile:98)
11-04 15:21:24.684 11259 11259 E AndroidRuntime: 	at b.sFDwyLqLVbegnoRB48qTKbev.L2AjfsueFUv(SourceFile:6)
11-04 15:21:24.684 11259 11259 E AndroidRuntime: 	at b.xvRukyE6vBCGurqY30yfCsGT0.run(SourceFile:109)
11-04 15:21:24.684 11259 11259 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:900)
11-04 15:21:24.684 11259 11259 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:103)
11-04 15:21:24.684 11259 11259 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:219)
11-04 15:21:24.684 11259 11259 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8668)
11-04 15:21:24.684 11259 11259 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-04 15:21:24.684 11259 11259 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
11-04 15:21:24.684 11259 11259 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
11-04 15:21:24.684 11259 11259 E AndroidRuntime: 	Suppressed: b.zgSeCLBwumpIUIyBztJK7j5PjG: [KqxRyIDqQxghyrmZWkCOo{Cancelling}@50ab7f2, Dispatchers.Main]
11-04 15:21:24.684 11259 11259 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
11-04 15:21:24.684 11259 11259 E AndroidRuntime: 	at com.android.server.LocationManagerService.checkResolutionLevelIsSufficientForProviderUseLocked(libmapleservices.so:5866796)
11-04 15:21:24.684 11259 11259 E AndroidRuntime: 	at com.android.server.LocationManagerService.requestLocationUpdates(libmapleservices.so:4936948)
11-04 15:21:24.684 11259 11259 E AndroidRuntime: 	at android.location.ILocationManager$Stub.onTransact(libmapleframework.so:5172068)
11-04 15:21:24.684 11259 11259 E AndroidRuntime: 	at com.android.server.HwLocationManagerService.onTransact(libmaplehwServices.so:2341244)
11-04 15:21:24.684 11259 11259 E AndroidRuntime: 	at android.os.Binder.execTransactInternal(libmapleframework.so:6255836)
11-04 15:21:24.684 11259 11259 E AndroidRuntime: callee: null 1656/2267
11-04 15:21:24.684 11259 11259 E AndroidRuntime: 
```

</details>

## Extra notes

Also tried `pm grant bitpit.launcher android.permission.ACCESS_FINE_LOCATION`:

<details>

```java
Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown permission: com.android.gps.FINE_LOCATION
	at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(libmapleservices.so:5697404)
	at com.android.server.pm.PackageManagerService.grantRuntimePermission(libmapleservices.so:11488396)
	at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(libmapleservices.so:14475992)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(libmapleservices.so:3859476)
	at android.os.ShellCommand.exec(libmapleframework.so:2618540)
	at com.android.server.pm.PackageManagerService.onShellCommand(libmapleservices.so:3900400)
	at android.os.Binder.onTransact(libmapleframework.so:3613832)
	at android.content.pm.IPackageManager$Stub.onTransact(libmapleframework.so:6186880)
	at com.android.server.pm.PackageManagerService.onTransact(libmapleservices.so:7791932)
	at com.android.server.pm.HwPackageManagerService.onTransact(libmaplehwServices.so:2475956)
	at android.os.Binder.execTransactInternal(libmapleframework.so:6255836)
	at android.os.Binder.execTransact(libmapleframework.so:6257632)
255|HWELS:/ $ pm grant bitpit.launcher android.permission.ACCESS_FINE_LOCATION                                                                                                                                                              
Security exception: Package bitpit.launcher has not requested permission android.permission.ACCESS_FINE_LOCATION

java.lang.SecurityException: Package bitpit.launcher has not requested permission android.permission.ACCESS_FINE_LOCATION
	at com.android.server.pm.permission.BasePermission.enforceDeclaredUsedAndRuntimeOrDevelopment(libmapleservices.so:5694384)
	at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(libmapleservices.so:5695384)
	at com.android.server.pm.PackageManagerService.grantRuntimePermission(libmapleservices.so:11488396)
	at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(libmapleservices.so:14475992)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(libmapleservices.so:3859476)
	at android.os.ShellCommand.exec(libmapleframework.so:2618540)
	at com.android.server.pm.PackageManagerService.onShellCommand(libmapleservices.so:3900400)
	at android.os.Binder.onTransact(libmapleframework.so:3613832)
	at android.content.pm.IPackageManager$Stub.onTransact(libmapleframework.so:6186880)
	at com.android.server.pm.PackageManagerService.onTransact(libmapleservices.so:7791932)
	at com.android.server.pm.HwPackageManagerService.onTransact(libmaplehwServices.so:2475956)
	at android.os.Binder.execTransactInternal(libmapleframework.so:6255836)
	at android.os.Binder.execTransact(libmapleframework.so:6257632)
```
If you are wondering what's `libmaple*.so`, it's basically a custom implementation of AndroidFramework in Huawei's HarmonyOS and does AOT to Dalvik bytecode and make calling conventions to the same as JNI. But honestly I don't think it matters with this issue.

</details>

Can you try declaring `android.permission.ACCESS_FINE_LOCATION` in manifest next release?

Thanks.

**Comment by mochaaP** [comment]
Hi @8bitPit do you have time to look into this? I believe this could just be a one line fix and once released I will test it ASAP.

**Comment by 8bitPit** [comment]
Thank you so much for reporting the issue in such detail @mochaaP. This one is a tricky issue. Requesting the location on non-Google-Play devices below Android 11 requires us to have the fine location permission, as you said. However, to my knowledge, if we grant the permission, we also have to update our Google Play App Content policy and state that we require the fine location permission—even though Niagara Launcher doesn't need the permission if it's downloaded from Google Play because then Google Play services are available. That's why we decided to instead ask the user to enter their location manually instead. Unfortunately, the [Geocoder API](https://developer.android.com/reference/android/location/Geocoder) from Android we use to convert the user's city to coordinates is also not available on every device (because the device manufacturer has to provide a backend). So if all these edge cases apply (below Android 11, no Google Play services, no Geocoder implementation), we added a form in v1.8.1 to let the user enter their location's coordinates. I know this is not pretty, as it's more cumbersome for the user, but only a handful of users will run into this issue, it works, and users only have to enter your location once. I apologize for the inconvenience; I hope it's understandable why we decided to add the form instead of the fine location permission request.

**Comment by mochaaP** [comment]
Hi, I found another weird case on my Pixel 4, running ProtonAOSP 12.4.1 (SQ3A.220705.003.A1) with GMS:

<details>

```log
11-13 23:44:13.467  5920 18673 I AlarmManager: set [name: FusedLocation:expire type: 2 triggerAtMillis: 195278775 windowMillis: 0 intervalMillis: 0]
11-13 23:44:13.486  1823  3638 W ActivityManager: Appop Denial: Accessing service com.google.android.gms/com.google.android.location.internal.server.GoogleLocationService from pid=5920, uid=10158 requires appop COARSE_LOCATION
```

</details>

Then the launcher just returns "Error". I have no idea why this happens, but seems other apps using the Geocoder API doesn't works too.

---

Maybe a bug in GrapheneOS's [GmsCompat](https://github.com/GrapheneOS/platform_packages_apps_GmsCompat) (always presented even using non-sandboxed GMS). AOSP is weird ¯\\\_(ツ)_/¯

Anyways, thank you for the efforts.

**Comment by 8bitPit** [comment]
Huh, that's a weird bug; this might explain why other users occasionally get an error message. Since we can't fix that issue and we provided a workaround for your original request, I hope it's okay for you if I close this ticket. Thanks again for your detailed bug reports!
